pipeline{
    options{
        timeout(time: 5, unit: "MINUTES")
    }
    parameters{
        string(name: "IP-Address", defaultValue: "192.168.2.79", description: "IP Address of Raspberry Pi on local network")
    }
    stages{
        stage("Ping raspberry pi"){
            sh "ping ${IP-Address}"
        }
    }
}